name: Push to ECR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-ecr-push-workflow:
    uses: ./.github/workflows/REUSE-docker-build-test-push-to-ecr.yml
    # uses: myorg/myrepo/.github/workflows/REUSE-docker-build-test-push-to-ecr.yml@main
    with:
      AWS_REGION: "us-east-1"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  call-eks-deploy-workflow:
    uses: ./.github/workflows/REUSE-eks-deploy.yml
    # uses: myorg/myrepo/.github/workflows/REUSE-eks-deploy.yml@main
    needs: call-ecr-push-workflow
    with:
      AWS_REGION: "us-east-1"
      EKS_CLUSTER_NAME: "demo-cluster"
      IMAGE: ${{ needs.call-ecr-push-workflow.outputs.image }}
      SERVICE_NAME: "spring-petclinic"
      ENVIRONMENT: "Prod"
    secrets: inherit
